#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Dec 27 19:37:45 2018

@author: r17935avinash
"""

from test_model_pytorch_facebook_challenge import calc_accuracy

import sys
sys.path.insert(0, 'deep-learning-flower-identifier')